#!/usr/bin/env python3
"""Pack sprites, fonts and sound effects from the c2-sans-fight project
(https://github.com/Jcw87/c2-sans-fight) into src/assets.js as data URIs, with
the hotspots / image points read from its .caproj so parts attach exactly as
in the original.

    git clone --depth 1 https://github.com/Jcw87/c2-sans-fight ../c2-sans-fight
    python3 tools/import_assets.py [path/to/c2-sans-fight]
Sounds are converted to mp3 (Safari cannot play ogg) with ffmpeg.
"""
import base64, glob, json, os, re, subprocess, sys, tempfile

SRC = sys.argv[1] if len(sys.argv) > 1 else '/home/user/jcw87/c2-sans-fight'
OUT = 'src/assets.js'
proj = open(glob.glob(os.path.join(SRC, '*.caproj'))[0], encoding='utf-8').read()

ANIMS = ['SansHead', 'SansBody', 'SansLegs', 'SansTorso', 'SansSweat', 'GasterBlaster', 'Strike',
         'Target', 'TargetChoice', 'PlayerHeart', 'HeartShard', 'UIFight', 'UIAct', 'UIItem', 'UIMercy', 'HP', 'KR', 'SpeechBubble']
TEXTURES = ['BattleFont', 'DamageFont', 'DefaultFont', 'BoneV']
SOUNDS = ['BoneStab', 'Ding', 'Flash', 'GasterBlast', 'GasterBlast2', 'GasterBlaster', 'HeartShatter', 'HeartSplit',
          'MenuCursor', 'MenuSelect', 'PlayerDamaged', 'PlayerFight', 'Slam', 'Warning', 'BattleText', 'SansSpeak']


def b64(path, mime):
    return 'data:%s;base64,%s' % (mime, base64.b64encode(open(path, 'rb').read()).decode())


def anim_meta(name):
    block = re.search(r'<object-type name="%s".*?</object-type>' % name, proj, re.S).group(0)
    out = {}
    for am in re.finditer(r'<animation[^>]*name="([^"]*)"[^>]*speed="([^"]*)"[^>]*>(.*?)</animation>', block, re.S):
        frames = []
        for f in re.finditer(r'<frame([^>]*)>(.*?)</frame>', am.group(3), re.S):
            attrs = dict(re.findall(r'(\w+)="([^"]*)"', f.group(1)))
            pts = {n: [float(x), float(y)] for n, x, y in re.findall(r'<image-point name="([^"]*)" x="([^"]*)" y="([^"]*)"', f.group(2))}
            frames.append(dict(hx=float(attrs.get('hotspotX', 0)), hy=float(attrs.get('hotspotY', 0)), pts=pts))
        out[am.group(1)] = dict(speed=float(am.group(2)), frames=frames)
    return out


assets = dict(img={}, meta={}, sfx={})
for name in ANIMS:
    meta = anim_meta(name)
    for anim, info in meta.items():
        files = sorted(glob.glob(os.path.join(SRC, 'Animations', name, anim, '*.png')))
        for i, f in enumerate(files):
            assets['img']['%s/%s/%d' % (name, anim, i)] = b64(f, 'image/png')
        info['n'] = len(files)
    assets['meta'][name] = meta
for name in TEXTURES:
    assets['img'][name] = b64(os.path.join(SRC, 'Textures', name + '.png'), 'image/png')
with tempfile.TemporaryDirectory() as td:
    for name in SOUNDS:
        dst = os.path.join(td, name + '.mp3')
        subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', os.path.join(SRC, 'Files', name + '.ogg'),
                        '-ac', '1', '-b:a', '96k', dst], check=True)
        assets['sfx'][name] = b64(dst, 'audio/mpeg')

with open(OUT, 'w') as f:
    f.write('// Generated by tools/import_assets.py from github.com/Jcw87/c2-sans-fight - do not edit.\n')
    f.write('window.MV_ASSETS = ')
    json.dump(assets, f, separators=(',', ':'))
    f.write(';\n')
print('images', len(assets['img']), 'sounds', len(assets['sfx']), 'bytes', os.path.getsize(OUT))
