#!/usr/bin/env python3
"""Bake GNU Unifont glyphs (8x16 ASCII, 16x16 CJK) into src/glyphs.js as bit rows.

    python3 tools/make_font.py
Unifont is a pixel font, so rendering it at 16 px gives exact 1-bit glyphs and
the player never depends on system fonts.
"""
from PIL import Image, ImageDraw, ImageFont
import json

FONT = '/usr/share/fonts/opentype/unifont/unifont.otf'
ASCII = ''.join(chr(c) for c in range(32, 127))
# every non-ASCII character used anywhere in src/ (dialogue, buttons, prompts)
import glob, re
CJK = '战斗行动物品仁慈' + '？！。，：…「」'
for f in glob.glob('src/*.js'):
    if f.endswith(('glyphs.js', 'assets.js', 'analysis.js')):
        continue
    CJK += ''.join(re.findall(r'[^\x00-\x7f]', open(f, encoding='utf-8').read()))
CJK = ''.join(ch for ch in dict.fromkeys(CJK) if ch.isprintable() and ch not in '♥')

font = ImageFont.truetype(FONT, 16)

def bake(ch, w):
    img = Image.new('1', (w, 16), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
    rows = []
    for y in range(16):
        v = 0
        for x in range(w):
            if img.getpixel((x, y)):
                v |= 1 << (w - 1 - x)
        rows.append(v)
    return rows

glyphs = {}
for ch in ASCII:
    glyphs[ch] = [8, bake(ch, 8)]
for ch in CJK:
    glyphs[ch] = [16, bake(ch, 16)]

with open('src/glyphs.js', 'w') as f:
    f.write('// Generated by tools/make_font.py from GNU Unifont - do not edit by hand.\n')
    f.write('window.MV_GLYPHS = ')
    json.dump(glyphs, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')

# preview
chars = '战斗行动物品仁慈 空气骤然凝固。 MISS BOMEI LV 19 HP 92/92'
img = Image.new('L', (16 * len(chars), 16), 0)
x = 0
for ch in chars:
    w, rows = glyphs.get(ch, [8, [0] * 16])
    for yy, r in enumerate(rows):
        for xx in range(w):
            if r >> (w - 1 - xx) & 1:
                img.putpixel((x + xx, yy), 255)
    x += w
img = img.crop((0, 0, x, 16)).resize((x * 4, 64), Image.NEAREST)
import sys
if len(sys.argv) > 1:
    img.save(sys.argv[1])
print(len(glyphs), 'glyphs')
